=== alvar91/hh-scool-xslt/doc.dtd
<?xml encoding="UTF-8"?>
        <!ENTITY nbsp "&#160;">
        <!ELEMENT doc (userInfo,navigationReferences,headerReferences,
                sliderSections)>
        <!ATTLIST doc
                xmlns CDATA #FIXED ''>

        <!ELEMENT userInfo (loginStatus,nickName,userCurrency,userCountry,
                userCity)>
        <!ATTLIST userInfo
                xmlns CDATA #FIXED ''>

        <!ELEMENT navigationReferences (reference)+>
        <!ATTLIST navigationReferences
                xmlns CDATA #FIXED ''>

        <!ELEMENT headerReferences (reference)+>
        <!ATTLIST headerReferences
                xmlns CDATA #FIXED ''>

        <!ELEMENT sliderSections (section)+>
        <!ATTLIST sliderSections
                xmlns CDATA #FIXED ''>

        <!ELEMENT loginStatus EMPTY>
        <!ATTLIST loginStatus
                xmlns CDATA #FIXED ''
                isLogged NMTOKEN #REQUIRED>

        <!ELEMENT nickName (#PCDATA)>
        <!ATTLIST nickName
                xmlns CDATA #FIXED ''>

        <!ELEMENT userCurrency EMPTY>
        <!ATTLIST userCurrency
                xmlns CDATA #FIXED ''
                type NMTOKEN #REQUIRED
                value CDATA #REQUIRED>

        <!ELEMENT userCountry (#PCDATA)>
        <!ATTLIST userCountry
                xmlns CDATA #FIXED ''>

        <!ELEMENT userCity (#PCDATA)>
        <!ATTLIST userCity
                xmlns CDATA #FIXED ''>

        <!ELEMENT section (description,productImage)>
        <!ATTLIST section
                xmlns CDATA #FIXED ''
                isActive NMTOKEN #IMPLIED>

        <!ELEMENT description (#PCDATA)>
        <!ATTLIST description
                xmlns CDATA #FIXED ''>

        <!ELEMENT productImage EMPTY>
        <!ATTLIST productImage
                xmlns CDATA #FIXED ''
                alt CDATA #IMPLIED
                src CDATA #REQUIRED>

        <!ELEMENT reference (#PCDATA)>
        <!ATTLIST reference
                xmlns CDATA #FIXED ''
                src CDATA #REQUIRED>

=== alvar91/hh-scool-xslt/doc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">

<doc>
    <userInfo>
        <loginStatus isLogged="false"/>
        <nickName>User123</nickName>
        <userCurrency type="rub" value="₽"/>
        <userCountry>Россия</userCountry>
        <userCity>Москва</userCity>
    </userInfo>

    <navigationReferences>
        <reference src="#">Шоурум</reference>
        <reference src="#">Оплата</reference>
        <reference src="#">Доставка</reference>
        <reference src="#">Самовывоз</reference>
        <reference src="#">Контактная информация</reference>
    </navigationReferences>

    <headerReferences>
        <reference src="#">Одежда</reference>
        <reference src="#">Сумки</reference>
        <reference src="#">Аксессуары</reference>
        <reference src="#">Офисные принадлежности</reference>
    </headerReferences>

    <sliderSections>
        <section isActive="true">
            <description>Мужская и женская одежда
                с символикой HeadHunter</description>
            <productImage src="css/slider-1.3b5e737a.png" alt="Мужская и женская одежда" />
        </section>
        <section>
            <description>Офисные принадлежности
                с символикой HeadHunter</description>
            <productImage src="css/slider-2.769fcb14.png" />
        </section>
    </sliderSections>
</doc>
